/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author misha
 */
public class McQuiz2 extends javax.swing.JFrame {

    /**
     * Creates new form McQuiz2
     */
    public McQuiz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q4Clbl = new javax.swing.JLabel();
        q4Dlbl = new javax.swing.JLabel();
        q4Resultlbl = new javax.swing.JLabel();
        answer5lbl = new javax.swing.JLabel();
        answer5txt = new javax.swing.JTextField();
        q5Part1lbl = new javax.swing.JLabel();
        q5Part2lbl = new javax.swing.JLabel();
        q5Albl = new javax.swing.JLabel();
        q5Blbl = new javax.swing.JLabel();
        q5Clbl = new javax.swing.JLabel();
        answer1lbl = new javax.swing.JLabel();
        q5Dlbl = new javax.swing.JLabel();
        answer1txt = new javax.swing.JTextField();
        q5Resultlbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        answer6lbl = new javax.swing.JLabel();
        correctlbl = new javax.swing.JLabel();
        answer6txt = new javax.swing.JTextField();
        incorrectlbl = new javax.swing.JLabel();
        q6Part1lbl = new javax.swing.JLabel();
        gradelbl = new javax.swing.JLabel();
        q6Part2lbl = new javax.swing.JLabel();
        correctOutputlbl = new javax.swing.JLabel();
        incorrectOutputlbl = new javax.swing.JLabel();
        gradeOutputlbl = new javax.swing.JLabel();
        answer2lbl = new javax.swing.JLabel();
        titlelbl = new javax.swing.JLabel();
        q1Part1lbl = new javax.swing.JLabel();
        q1Part2lbl = new javax.swing.JLabel();
        q1Albl = new javax.swing.JLabel();
        q1Blbl = new javax.swing.JLabel();
        q1Clbl = new javax.swing.JLabel();
        q1Dlbl = new javax.swing.JLabel();
        q6Albl = new javax.swing.JLabel();
        q6Blbl = new javax.swing.JLabel();
        q6Clbl = new javax.swing.JLabel();
        q6Dlbl = new javax.swing.JLabel();
        answer2txt = new javax.swing.JTextField();
        q6Resultlbl = new javax.swing.JLabel();
        q2Part1lbl = new javax.swing.JLabel();
        bonusGradelbl = new javax.swing.JLabel();
        q2Part2lbl = new javax.swing.JLabel();
        q2Albl = new javax.swing.JLabel();
        q2Blbl = new javax.swing.JLabel();
        q2Clbl = new javax.swing.JLabel();
        q2Dlbl = new javax.swing.JLabel();
        q1Resultlbl = new javax.swing.JLabel();
        q2Resultlbl = new javax.swing.JLabel();
        answer3lbl = new javax.swing.JLabel();
        answer3txt = new javax.swing.JTextField();
        q3Part1lbl = new javax.swing.JLabel();
        q3Part2lbl = new javax.swing.JLabel();
        q3Albl = new javax.swing.JLabel();
        q3Blbl = new javax.swing.JLabel();
        q3Clbl = new javax.swing.JLabel();
        q3Dlbl = new javax.swing.JLabel();
        q3Resultlbl = new javax.swing.JLabel();
        answer4lbl = new javax.swing.JLabel();
        answer4txt = new javax.swing.JTextField();
        q4Part1lbl = new javax.swing.JLabel();
        q4Part2lbl = new javax.swing.JLabel();
        q4Albl = new javax.swing.JLabel();
        q4Blbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        q4Clbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q4Clbl.setText("C) Amylopectin");

        q4Dlbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q4Dlbl.setText("D) Cellulose");

        answer5lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        answer5lbl.setText("Your answer:");

        answer5txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer5txtActionPerformed(evt);
            }
        });

        q5Part1lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q5Part1lbl.setText("5. Which of the following is a function");

        q5Part2lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q5Part2lbl.setText("of lipids in human cells?");

        q5Albl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q5Albl.setText("A) Quick energy source");

        q5Blbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q5Blbl.setText("B) Breaking down carbohydrates");

        q5Clbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q5Clbl.setText("C) Catalyzing hydrolysis reactions");

        answer1lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        answer1lbl.setText("Your answer:");

        q5Dlbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q5Dlbl.setText("D) Producing hormones");

        answer1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1txtActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        answer6lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        answer6lbl.setText("Your answer:");

        correctlbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        correctlbl.setText("Number of correct answers:");

        answer6txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer6txtActionPerformed(evt);
            }
        });

        incorrectlbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        incorrectlbl.setText("Number of incorrect answers:");

        q6Part1lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q6Part1lbl.setText("6. Which of these statements about starch");

        gradelbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        gradelbl.setText("Grade:");

        q6Part2lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q6Part2lbl.setText("is incorrect?");

        answer2lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        answer2lbl.setText("Your answer:");

        titlelbl.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        titlelbl.setText("Summative Quiz 1: Carbohydrates, Lipids, and Proteins");

        q1Part1lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q1Part1lbl.setText("1. What kind of bonds are used to hold together ");

        q1Part2lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q1Part2lbl.setText("the amino acids in a polypeptide chain?");

        q1Albl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q1Albl.setText("A) Phosphodiester bonds");

        q1Blbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q1Blbl.setText("B) Ester bonds");

        q1Clbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q1Clbl.setText("C) Peptide bonds");

        q1Dlbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q1Dlbl.setText("D) Ionic bonds");

        q6Albl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q6Albl.setText("A) It is a complex carbohydrate");

        q6Blbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q6Blbl.setText("B) There are two forms of starch");

        q6Clbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q6Clbl.setText("C) Starch is made of Beta- glucose monomers");

        q6Dlbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q6Dlbl.setText("D) Starch is made by plants but can be used by animals");

        answer2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2txtActionPerformed(evt);
            }
        });

        q2Part1lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q2Part1lbl.setText("2. What level of protein organization includes the");

        bonusGradelbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        q2Part2lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q2Part2lbl.setText("polypeptide chain's interactions with the environment?");

        q2Albl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q2Albl.setText("A) Primary");

        q2Blbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q2Blbl.setText("B) Secondary");

        q2Clbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q2Clbl.setText("C) Tertiary");

        q2Dlbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q2Dlbl.setText("D) Quaternary");

        answer3lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        answer3lbl.setText("Your answer:");

        answer3txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3txtActionPerformed(evt);
            }
        });

        q3Part1lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q3Part1lbl.setText("3. Which amino acid contains the ");

        q3Part2lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q3Part2lbl.setText("R-group -SH?");

        q3Albl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q3Albl.setText("A) Cysteine");

        q3Blbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q3Blbl.setText("B) Tryptophan");

        q3Clbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q3Clbl.setText("C) Isoleucine");

        q3Dlbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q3Dlbl.setText("D) Glutamine");

        answer4lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        answer4lbl.setText("Your answer:");

        answer4txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4txtActionPerformed(evt);
            }
        });

        q4Part1lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q4Part1lbl.setText("4. Which of the following compounds is not");

        q4Part2lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q4Part2lbl.setText("a complex carbohydrate?");

        q4Albl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q4Albl.setText("A) Glycogen");

        q4Blbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        q4Blbl.setText("B) Glycerol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1Blbl)
                            .addComponent(q1Clbl)
                            .addComponent(q1Dlbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer1lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(answer1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q1Resultlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(q1Albl))
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(q2Part2lbl)
                            .addComponent(q2Part1lbl)
                            .addComponent(q4Part2lbl)
                            .addComponent(q4Part1lbl)
                            .addComponent(q6Part2lbl)
                            .addComponent(q6Part1lbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q2Blbl)
                                    .addComponent(q2Clbl)
                                    .addComponent(q2Dlbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(answer2lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(answer2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(q2Resultlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(q2Albl)
                                    .addComponent(q4Blbl)
                                    .addComponent(q4Clbl)
                                    .addComponent(q4Dlbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(answer4lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(answer4txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(q4Resultlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(q4Albl)
                                    .addComponent(q6Blbl)
                                    .addComponent(q6Clbl)
                                    .addComponent(q6Dlbl)
                                    .addComponent(q6Albl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(answer6lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(answer6txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(q6Resultlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titlelbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(correctlbl)
                        .addGap(18, 18, 18)
                        .addComponent(correctOutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(bonusGradelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(incorrectlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(incorrectOutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(gradelbl)
                                .addGap(28, 28, 28)
                                .addComponent(gradeOutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1Part2lbl)
                    .addComponent(q1Part1lbl)
                    .addComponent(q3Part2lbl)
                    .addComponent(q3Part1lbl)
                    .addComponent(q5Part2lbl)
                    .addComponent(q5Part1lbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q3Blbl)
                            .addComponent(q3Clbl)
                            .addComponent(q3Dlbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer3lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(answer3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q3Resultlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(q3Albl)
                            .addComponent(q5Blbl)
                            .addComponent(q5Clbl)
                            .addComponent(q5Dlbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(answer5lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(answer5txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q5Resultlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(q5Albl))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlelbl)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q1Part1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q1Part2lbl)
                        .addGap(18, 18, 18)
                        .addComponent(q1Albl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q1Blbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q1Clbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q1Dlbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1Resultlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(answer1lbl)
                                .addComponent(answer1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q2Part1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q2Part2lbl)
                        .addGap(18, 18, 18)
                        .addComponent(q2Albl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q2Blbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q2Clbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q2Dlbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q2Resultlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(answer2lbl)
                                .addComponent(answer2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q3Part1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q3Part2lbl)
                        .addGap(18, 18, 18)
                        .addComponent(q3Albl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q3Blbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q3Clbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q3Dlbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q3Resultlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(answer3lbl)
                                .addComponent(answer3txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(q4Part1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q4Part2lbl)
                        .addGap(18, 18, 18)
                        .addComponent(q4Albl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q4Blbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q4Clbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q4Dlbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q4Resultlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(answer4lbl)
                                .addComponent(answer4txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(q5Part1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q5Part2lbl)
                        .addGap(18, 18, 18)
                        .addComponent(q5Albl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q5Blbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q5Clbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q5Dlbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q5Resultlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(answer5lbl)
                                .addComponent(answer5txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(q6Part1lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q6Part2lbl)
                        .addGap(18, 18, 18)
                        .addComponent(q6Albl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q6Blbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q6Clbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q6Dlbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q6Resultlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(answer6lbl)
                                .addComponent(answer6txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bonusGradelbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(incorrectlbl)
                        .addComponent(correctlbl)
                        .addComponent(gradeOutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gradelbl))
                    .addComponent(correctOutputlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incorrectOutputlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answer5txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer5txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer5txtActionPerformed

    private void answer1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Answer key
        //Q1
        final String answer1Lowercase = "c";
        final String answer1Uppercase = "C";
        //Q2
        final String answer2Lowercase = "c";
        final String answer2Uppercase = "C";
        //Q3
        final String answer3Lowercase = "a";
        final String answer3Uppercase = "A";
        //Q4
        final String answer4Lowercase = "b";
        final String answer4Uppercase = "B";
        //Q5
        final String answer5Lowercase = "d";
        final String answer5Uppercase = "D";
        //Q6
        final String answer6Lowercase = "c";
        final String answer6Uppercase = "C";

        //Scoring
        int correctAnswers = 0;
        int incorrectAnswers = 0;
        int bonusMark = (int)Math.round(Math.random()*1+1);

        //Question 1
        String userAnswer1;
        userAnswer1 = answer1txt.getText();
        if (userAnswer1.equals(answer1Lowercase) || userAnswer1.equals(answer1Uppercase)) {
            correctAnswers = correctAnswers +1 ;
            q1Resultlbl.setText("Correct!");
        }
        else {
            incorrectAnswers = incorrectAnswers + 1;
            q1Resultlbl.setText("Incorrect");
        }

        //Question 2
        String userAnswer2;
        userAnswer2 = answer2txt.getText();
        if (userAnswer2.equals(answer2Lowercase) || userAnswer2.equals(answer2Uppercase)) {
            correctAnswers = correctAnswers +1 ;
            q2Resultlbl.setText("Correct!");
        }
        else {
            incorrectAnswers = incorrectAnswers + 1;
            q2Resultlbl.setText("Incorrect!");
        }

        //Question 3
        String userAnswer3;
        userAnswer3 = answer3txt.getText();
        if (userAnswer3.equals(answer3Lowercase) || userAnswer3.equals(answer3Uppercase)) {
            correctAnswers = correctAnswers +1 ;
            q3Resultlbl.setText("Correct!");
        }
        else {
            incorrectAnswers = incorrectAnswers + 1;
            q3Resultlbl.setText("Incorrect!");
        }

        //Question 4
        String userAnswer4;
        userAnswer4 = answer4txt.getText();
        if (userAnswer4.equals(answer4Lowercase) || userAnswer4.equals(answer4Uppercase)) {
            correctAnswers = correctAnswers +1 ;
            q4Resultlbl.setText("Correct!");
        }
        else {
            incorrectAnswers = incorrectAnswers + 1;
            q4Resultlbl.setText("Incorrect!");
        }

        //Question 5
        String userAnswer5;
        userAnswer5 = answer5txt.getText();
        if (userAnswer5.equals(answer5Lowercase) || userAnswer5.equals(answer5Uppercase)) {
            correctAnswers = correctAnswers +1 ;
            q5Resultlbl.setText("Correct!");
        }
        else {
            incorrectAnswers = incorrectAnswers + 1;
            q5Resultlbl.setText("Incorrect!");
        }

        //Question 6
        String userAnswer6;
        userAnswer6 = answer6txt.getText();
        if (userAnswer6.equals(answer6Lowercase) || userAnswer6.equals(answer6Uppercase)) {
            correctAnswers = correctAnswers +1 ;
            q6Resultlbl.setText("Correct!");
        }
        else {
            incorrectAnswers = incorrectAnswers + 1;
            q6Resultlbl.setText("Incorrect!");
        }

        //Grade calculation
        double grade;
        grade = ((double)correctAnswers / 6) * 100;
        grade = Math.round(grade);

        //Bonus marks
        if (bonusMark == 1) {
            grade = grade+5;
            bonusGradelbl.setText("5 bonus marks for you!");
        }
        //No bonus marks
        if (bonusMark == 2) {
            bonusGradelbl.setText("No bonus marks for you!");
        }

        //Outputs
        correctOutputlbl.setText(String.valueOf(correctAnswers));
        incorrectOutputlbl.setText(String.valueOf(incorrectAnswers));
        gradeOutputlbl.setText(String.valueOf(grade) + "%");

        //System.out.println(bonusMark);
        //System.out.println(grade);
        //System.out.println("correct " + correctAnswers);
        //System.out.println("incorrect " + incorrectAnswers);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void answer6txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer6txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer6txtActionPerformed

    private void answer2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2txtActionPerformed

    private void answer3txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer3txtActionPerformed

    private void answer4txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer4txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(McQuiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(McQuiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(McQuiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(McQuiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new McQuiz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer1lbl;
    private javax.swing.JTextField answer1txt;
    private javax.swing.JLabel answer2lbl;
    private javax.swing.JTextField answer2txt;
    private javax.swing.JLabel answer3lbl;
    private javax.swing.JTextField answer3txt;
    private javax.swing.JLabel answer4lbl;
    private javax.swing.JTextField answer4txt;
    private javax.swing.JLabel answer5lbl;
    private javax.swing.JTextField answer5txt;
    private javax.swing.JLabel answer6lbl;
    private javax.swing.JTextField answer6txt;
    private javax.swing.JLabel bonusGradelbl;
    private javax.swing.JLabel correctOutputlbl;
    private javax.swing.JLabel correctlbl;
    private javax.swing.JLabel gradeOutputlbl;
    private javax.swing.JLabel gradelbl;
    private javax.swing.JLabel incorrectOutputlbl;
    private javax.swing.JLabel incorrectlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel q1Albl;
    private javax.swing.JLabel q1Blbl;
    private javax.swing.JLabel q1Clbl;
    private javax.swing.JLabel q1Dlbl;
    private javax.swing.JLabel q1Part1lbl;
    private javax.swing.JLabel q1Part2lbl;
    private javax.swing.JLabel q1Resultlbl;
    private javax.swing.JLabel q2Albl;
    private javax.swing.JLabel q2Blbl;
    private javax.swing.JLabel q2Clbl;
    private javax.swing.JLabel q2Dlbl;
    private javax.swing.JLabel q2Part1lbl;
    private javax.swing.JLabel q2Part2lbl;
    private javax.swing.JLabel q2Resultlbl;
    private javax.swing.JLabel q3Albl;
    private javax.swing.JLabel q3Blbl;
    private javax.swing.JLabel q3Clbl;
    private javax.swing.JLabel q3Dlbl;
    private javax.swing.JLabel q3Part1lbl;
    private javax.swing.JLabel q3Part2lbl;
    private javax.swing.JLabel q3Resultlbl;
    private javax.swing.JLabel q4Albl;
    private javax.swing.JLabel q4Blbl;
    private javax.swing.JLabel q4Clbl;
    private javax.swing.JLabel q4Dlbl;
    private javax.swing.JLabel q4Part1lbl;
    private javax.swing.JLabel q4Part2lbl;
    private javax.swing.JLabel q4Resultlbl;
    private javax.swing.JLabel q5Albl;
    private javax.swing.JLabel q5Blbl;
    private javax.swing.JLabel q5Clbl;
    private javax.swing.JLabel q5Dlbl;
    private javax.swing.JLabel q5Part1lbl;
    private javax.swing.JLabel q5Part2lbl;
    private javax.swing.JLabel q5Resultlbl;
    private javax.swing.JLabel q6Albl;
    private javax.swing.JLabel q6Blbl;
    private javax.swing.JLabel q6Clbl;
    private javax.swing.JLabel q6Dlbl;
    private javax.swing.JLabel q6Part1lbl;
    private javax.swing.JLabel q6Part2lbl;
    private javax.swing.JLabel q6Resultlbl;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
